set -x
db2 connect to test
db2 UPDATE DATABASE CONFIGURATION FOR test USING SELF_TUNING_MEM OFF;
db2 UPDATE DATABASE CONFIGURATION FOR test USING LOGBUFSZ       4300;
db2 UPDATE DATABASE CONFIGURATION FOR test USING NUM_IOCLEANERS   16;
db2 UPDATE DATABASE CONFIGURATION FOR test USING DBHEAP         5231;

db2 AUTOCONFIGURE USING MEM_PERCENT 50 WORKLOAD_TYPE MIXED APPLY NONE;

db2 connect reset
db2stop force
db2start
