set -x
db2 connect to dbgen4
db2 UPDATE DATABASE CONFIGURATION FOR dbgen4 USING SELF_TUNING_MEM OFF;
db2 UPDATE DATABASE CONFIGURATION FOR dbgen4 USING LOGBUFSZ       4300;
db2 UPDATE DATABASE CONFIGURATION FOR dbgen4 USING NUM_IOCLEANERS   16;
db2 UPDATE DATABASE CONFIGURATION FOR dbgen4 USING DBHEAP         5231;

db2 AUTOCONFIGURE USING MEM_PERCENT 50 WORKLOAD_TYPE MIXED APPLY NONE;

db2 connect reset
db2stop force
db2start
